name: dashmon
description: A cli tool to run Flutter applications and auto hot reload it when files are changed
version: 0.0.1
homepage: https://github.com/erickzanardo/dashmon

executables:
  dashmon:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
